sudo: false
language: elixir
elixir:
  - 1.6.0
otp_release:
  - 20.3
cache:
  directories:
    - _build
    - deps
script:
  - mix test || travis_terminate 1
  - mix format --check-formatted || travis_terminate 1
after_script:
  - MIX_ENV=docs mix do deps.get, inch.report
